version: "1.0"

services:
  django_server:
    build: ./backend/django_server/
    hostname: django_server
    command: >
      sh -c "python manage.py migrate &&
            hypercorn django_server.asgi:application --bind 0.0.0.0:8001 --reload -w 2 --keep-alive 30 --access-logfile '-'"
    env_file:
      - ./.env
    volumes:
      - ./backend/django_server/:/django_server/
    expose:
      - 8001
    ports:
      - "8001:8001"
    networks:
      - django_server_net
    restart: "always"

  fastapi_server:
    build: ./backend/fastapi_server/
    hostname: fastapi_server
    command: >
      sh -c "uvicorn main:app --reload"
    env_file:
      - ./.env
    volumes:
      - ./backend/fastapi_server/:/fastapi_server/
    expose:
      - 8002
    ports:
      - "8002:8002"
    networks:
      - fastapi_server_net
    restart: "always"

  gin_server:
    build: ./backend/gin_server/
    hostname: gin_server
    command: >
      sh -c "go mod download && go mod tidy && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main && go run main.go"
    env_file:
      - ./.env
    volumes:
      - ./backend/gin_server/:/gin_server/
    expose:
      - 8003
    ports:
      - "8003:8003"
    networks:
      - gin_server_net
    restart: "always"

  nodejs_server:
    build: ./backend/nodejs_server/
    hostname: nodejs_server
    command: >
      sh -c "npm install && npm start"
    env_file:
      - ./.env
    volumes:
      - ./backend/nodejs_server/:/nodejs_server/
    expose:
      - 8004
    ports:
      - "8004:8004"
    networks:
      - nodejs_server_net
    restart: "always"

networks:
  django_server_net:
    driver: bridge

  fastapi_server_net:
    driver: bridge

  gin_server_net:
    driver: bridge

  nodejs_server_net:
    driver: bridge

volumes:
  django_server_data:
  fastapi_server_data:
  gin_server_data:
  nodejs_server_data:
