name: Gocheck

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.16.1']
    name: Go ${{ matrix.go }} sample
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'gin_server/go.mod'
          go-version: ${{ matrix.go }}
      - run: go run main.go
